apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pic-viewer.fullname" . }}
  labels:
    {{- include "pic-viewer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pic-viewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pic-viewer.selectorLabels" . | nindent 8 }}
    spec:
    # {{- with .Values.imagePullSecrets }}
    #   imagePullSecrets:
    #     {{- toYaml . | nindent 8 }}
    # {{- end }}
    #   serviceAccountName: {{ include "pic-viewer.serviceAccountName" . }}
    #   securityContext:
    #     {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.appVersion }}"
          #image: ntdtfr/pic-viewer:1.0
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FLASK_ENV
              value: "development"
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3  
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 3
            timeoutSeconds: 2
            successThreshold: 2
            failureThreshold: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
