{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pic-viewer.serviceAccountName" . }}
  labels:
{{ include "pic-viewer.labels" . | nindent 4 }}
{{- end -}}
