apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik.fullname" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      nodePort: {{ .Values.service.http.nodePort }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.https.port }}
      nodePort: {{ .Values.service.https.nodePort }}
      targetPort: {{ .Values.service.https.targetPort }}
      protocol: TCP
      name: https
    - port: {{ .Values.service.admin.port }}
      nodePort: {{ .Values.service.admin.nodePort }}
      targetPort: {{ .Values.service.admin.targetPort }}
      protocol: TCP
      name: admin
  selector:
    {{- include "traefik.selectorLabels" . | nindent 4 }}
