apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik.fullname" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      nodePort: {{ .Values.service.http.nodePort }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
    - name: https
      port: {{ .Values.service.https.port }}
      nodePort: {{ .Values.service.https.nodePort }}
      targetPort: {{ .Values.service.https.targetPort }}
      protocol: TCP
    - name: admin
      protocol: TCP
      port: {{ .Values.service.admin.port }}
      nodePort: {{ .Values.service.admin.nodePort }}
      targetPort: {{ .Values.service.admin.targetPort }}
    - name: streaming
      protocol: UDP
      port: {{ .Values.service.streaming.port }}
      nodePort: {{ .Values.service.streaming.nodePort }}
      targetPort: {{ .Values.service.streaming.targetPort }}
      
      
  selector:
    {{- include "traefik.selectorLabels" . | nindent 4 }}
